name: Publish Docker Image DH

on:
  push:
    branches: [ main ]
  release:
    types:
      -  published
  workflow_dispatch:

jobs:

  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    if: "!contains(github.event.head_commit.message, 'skip ci dh')"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image    
      run: docker build . --file Dockerfile --tag corvinuslucian/caddy-cf:latest
      
    - name: Push the Docker image to Docker Hub    
      run: docker login -u corvinuslucian -p ${{ secrets.DOCKER_TOKEN }} && docker push corvinuslucian/caddy-cf:latest
