name: Publish Docker image

on:
  push:
    branches: [ latest ]
  release:
    types:
      -  published
  workflow_dispatch:

jobs:
  build-docker-images:
    name: Build Docker Images
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
          
      - id: lowercase-repo-name
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
        
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      #https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables=
      #https://github.com/docker/build-push-action
      - name: Build and Push container image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          build-args: CADDY_VERSION=${{ secrets.CADDY_VERSION }}
          tags: |
            ${{ steps.lowercase-repo-name.outputs.lowercase }}:latest
            ${{ steps.lowercase-repo-name.outputs.lowercase }}:${{ secrets.CADDY_VERSION }}
            ghcr.io/${{ steps.lowercase-repo-name.outputs.lowercase }}:latest
            ghcr.io/${{ steps.lowercase-repo-name.outputs.lowercase }}:${{ secrets.CADDY_VERSION }}
